# Generated by Django 4.1 on 2023-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
    ]
