# Generated by Django 4.1 on 2023-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customerdetails_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
