# Generated by Django 4.1 on 2023-01-31 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='accounts.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(null=True),
        ),
    ]
