# Generated by Django 4.1 on 2023-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(related_name='customer_details', to='accounts.customerdetails'),
        ),
    ]
