# Generated by Django 4.1 on 2023-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
