# Generated by Django 4.1 on 2023-04-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_top',
            field=models.BooleanField(null=True),
        ),
    ]
